### ISSUE TITLE
Dependency Conflicts During Environment Setup

### ISSUE THREAD

**Issue by IliasChair** [atomicarchitects/DeNS#2]
Hello,
I encountered a series of dependency conflicts while attempting to install the required dependencies as outlined in the [Environment Setup guide](https://github.com/atomicarchitects/DeNS/blob/main/docs/env_setup.md). Specifically, running the following command:

``conda env create -f env/equiformer_v2_torch1_ocp2.yml``
results in an extensive list of conflicts, which I've documented in the attached text file. These conflicts occur regardless of whether I use a Linux or Windows machine, and I experienced the same issues with both conda and mamba.

Any guidance or a potential fix would be greatly appreciated.

Thank you for your support.

Best regards,
Ilias
[conflicts.txt](https://github.com/user-attachments/files/16748643/conflicts.txt)

**Comment by yilunliao** [comment]
Hi. Did the conflict happen during conda install or pip install?

**Comment by IliasChair** [comment]
I tried to install the environment exactly as specified using conda. And after that did not work, I attempted it again using mamba. I have not tried using pip yet, but I  think doing so would result in the same conflicts.

**Comment by yilunliao** [comment]
Hi @IliasChair 

I was able to create a new env based on the docs several days ago.

If you still have a problem, can you please let me know more details on the server/machine you use or the entire error message?
I am guessing some env variables result in the conflict.

**Comment by IliasChair** [comment]
Hello again,
The issue seemed to stem from incompatibilities with the PyTorch/CUDA versions. I was able to resolve it by instead using the installation instructions on the OCP Documentation page with PyTorch and CUDA 11.8. I’m running the code on an HPC cluster with Linux ROCKY 8.10.
However since creating this issue, changes to Conda’s licensing have complicated things for me, so I’ve put this on hold for now. I’ll close the issue for the moment and revisit it when I can provide better feedback. Thanks for your help!

**Comment by yilunliao** [comment]
I see. Then I guess the issue is probably because of CUDA version. But glad that you figure this out, and sorry I was not able to provide much help.
